@echo off
echo Starting LearnHub Backend...
echo.
echo Navigating to server directory...
cd server
echo.
echo Installing dependencies...
call npm install
echo.
echo Seeding database with sample data...
call npm run seed
echo.
echo Starting development server...
call npm run dev
pause
